### ISSUE TITLE
Test fails "Error: failed to convert file"

### ISSUE THREAD

**Issue by lakenen** [ryancole/topdf#1]
I was able to build the library, but when I run the test, it fails with no explanation as to why. Any idea why this would be happening? I am running on ubuntu 12.04 (64bit).

Thanks!

**Comment by ryancole** [comment]
I'll look into it when I get home in about an hour and a half. I'll probably either just add a few console print lines to pinpoint your exact error, or look into returning actual informative errors. :)

The failure is occurring within the C++ code, though.

Did you specify the font directory setting? By default, it will be `/usr/share/fonts/truetype/msttcorefonts`. If that does not exist for you, then you need to install that font package using aptitude. I believe that the package is called something like `msttcorefonts` or `ttf-something`.

**Comment by lakenen** [comment]
Thanks for checking this. I changed the default directory, and now ~~it's giving me this error:~~

```
module.js:485                                                                                                                       │Font substitution: Font 'Century Gothic' has not been found. Using 'Times New Roman' font instead.                       
  process.dlopen(filename, module.exports);                                                                                         │                                                                                                                         
          ^                                                                                                                         │Font substitution: Font 'Century Gothic' has not been found. Using 'Times New Roman' font instead.                       
Error: libsc_ex.so: cannot open shared object file: No such file or directory                                                       │ Done!                                                                                                                   
    at Object.Module._extensions..node (module.js:485:11)                                                                           │Converting /home/ubuntu/docs/summary_of_major_changes.doc...                                                             
    at Module.load (module.js:356:32)                                                                                               │Font substitution: Font 'Symbol' has not been found. Using 'Times New Roman' font instead.                               
    at Function.Module._load (module.js:312:12)                                                                                     │ Done!                                                                                                                   
    at Module.require (module.js:362:17)                                                                                            │Converting /home/ubuntu/docs/test.doc...                                                                                 
    at require (module.js:378:17)                                                                                                   │Font substitution: Font 'Symbol' has not been found. Using 'Times New Roman' font instead.                               
    at Object.<anonymous> (/home/ubuntu/topdf/lib/topdf.js:6:13)                                                                    │ Done!                                                                                                                   
    at Module._compile (module.js:449:26)                                                                                           │Converting /home/ubuntu/docs/trustee_application_revised.doc...                                                          
    at Object.Module._extensions..js (module.js:467:10)                                                                             │Font substitution: Font 'Copperplate Gothic Bold' has not been found. Using 'Times New Roman' font instead.              
    at Module.load (module.js:356:32)                                                                                               │ Done!                                                                                                                   
    at Function.Module._load (module.js:312:12)   
```

Nevermind that ^... somehow my $LD_LIBRARY_PATH got reset. I fixed that, and now I'm getting the same ol' `[Error: failed to convert file]`.

**Comment by ryancole** [comment]
Ok, I'm working on this right now. I'm going to try to add in some actually useful error responses from the C++ side of things.

**Comment by lakenen** [comment]
I got it working. I had the fonts in sub-directories of my `fontdirectory`. Moving the fonts to a flat file structure fixed it. Thanks for the help!

Question: is there any error/warning generated if a required font is not found? Is it silently replaced with a similar font?

**Comment by ryancole** [comment]
Try updating the module and running `npm test`, if your font directory is the same as the one I mentioned above. Otherwise, add the font directory setting to the test file and then run `npm test`. Alternatively, run it in your own code. Either way, I added some actual error outputs. When calling the convert function, please paste the error that is reported back after it fails.

I updated it on NPM, as well.

Thanks.

**Comment by ryancole** [comment]
Oh, alright cool. Yea, the fonts have to be in the exact folder that you specify. That's not because of my code, it's just how Oracle's PDF export works. It doesn't traverse recursively looking for fonts.

If the font is not found, the Oracle tool defaults to Arial. There's no error generated. The default font is actually configurable, and I can add it as an option to this module if needed. I had no need, because Arial was fine, though. If you need it, I can try adding it in.

The documentation for the library itself, from Oracle, might explain it better. If you have the docs handy, the setting that specifies font is `SCCOPT_DEFAULTPRINTFONT`.

**Comment by lakenen** [comment]
Thanks! It's much appreciated! No need to add that for me, though I could see it being a potentially useful feature in the future.
