### ISSUE TITLE
Install failed on Arch Linux

### ISSUE THREAD

**Issue by diginfo** [ryancole/topdf#4]
Hi;

I just downloaded and installed the ORACLE source files and copied into folders, however when I try a npm install topdf I get the following error:

```
topdf.target.mk:83: recipe for target 'Release/obj.target/topdf/src/topdf.o' failed
make: *** [Release/obj.target/topdf/src/topdf.o] Error 1
make: Leaving directory '/usr/share/nodejs/dev/src/pure/node_modules/topdf/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.19.2-1-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/share/nodejs/dev/src/pure/node_modules/topdf
gyp ERR! node -v v0.12.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.19.2-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "--save" "install" "topdf" "--python=python2.7"
npm ERR! node v0.12.1
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! topdf@0.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the topdf@0.0.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the topdf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls topdf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/share/nodejs/dev/src/pure/node_modules/npm-debug.log
```

Any ideas ?

**Comment by ryancole** [comment]
It has been awhile since I've tried to compile this. I've got to step out for about an hour, but when I return I'll pull down this code and give it a fresh run-through.

**Comment by diginfo** [comment]
Great, thanks, I will be around for a couple of hours tonight (UK Time).

**Comment by ryancole** [comment]
I tried installing Arch Linux. I didn't realize it was such a manual install process. So, I'm just going to try this out on Ubuntu.

It looks like the node-gyp version has increased quite a bit, and it looks like there's some breaking changes. This doesn't seem to compile on the latest version of node. I see you're using node `0.12.1`, and node-gyp `1.0.3`. I'm currently using node `0.12.7`, and node-gyp `2.0.1`.

Is this a version of node installed from some package manager, or is this a version of node you specifically chose? It looks like `node-gyp` took a major version bump some time in between the version of node I'm running and the version you're running. I'm not sure if I should pursue updating to be useful with modern node-gyp, or to find the version of node you're running and figure that out. Are you able to update node?

**Comment by ryancole** [comment]
Actually nevermind, I just downgraded to node-gyp `1.0.3` and I'm getting the same errors. Maybe I'm missing something.

**Comment by ryancole** [comment]
I think I'm actually getting the same error as you are. It looks like both `libuv` and `v8` have had some breaking changes since I last coded this. I wish I made note of the versions of these libs from that time. This won't be something I'll have resolved tonight. I'll likely have to wait until this upcoming weekend so that I can devote a few nights to updating these dependencies.

**Comment by diginfo** [comment]
Hi, yes ARCH is a bit tricky to install, but this is not a new install and is an existing application which currently uses unoconv and libreoffice, but it is very slow.

**Comment by diginfo** [comment]
Hello, just wondering if you were able to investigate this issue ?

**Comment by ryancole** [comment]
Yea, I was able to. Both `libuv` and `v8` have made some breaking changes it looks like. I originally wrote this code almost 3 years ago and have not updated it against newer versions of those libraries. With my current schedule, updating this will be a here-and-there process. I'll try my best to make some progress some time this weekend. If the changes to `v8` and `libuv` aren't very big, perhaps one session of coding will be enough to adjust the code.
